### ISSUE TITLE
Back Button on Dashboard

### ISSUE THREAD

**Issue by PTremper** [SmartAQnet/dashboard#6]
Wir brauchen einen button der uns wieder von einem datastream zu dem thing zurückbringt damit wirs nicht jedesmal wieder in der ganzen liste suchen müssen wenn wir einen anderen datastream zu dem thing anschauen wollen. Typisches Userproblem, "was ist mein PM10 wert? aha cool. Was ist mein PM2.5 wert? wie komm ich da jetzt hin? wieder ganze liste anschauen, shit, welches war nochmal meins? ... " und so

**Comment by riedel** [comment]
warum bin ich der assignee hier?

**Comment by PTremper** [comment]
Weiß ich nicht mehr, aber wir haben auch einen Back Button, das ganze ist erledigt.
